### ISSUE TITLE
Meta Property "Categories"

### ISSUE THREAD

**Issue by HatiGamedev** [benui-dev/benui-site#1]
On the UPROPERTY page there is a nice meta uproperty missing "Categories"

Which can be used to limit the scope of FGameplayTags :)

```
UPROPERTY(EditAnywhere, meta=(Categories="Status"))
FGameplayTag LooseStatus;
```

Now designers can only select sub-tags of "Status" like "Status.Rooted"

**Comment by HatiGamedev** [comment]
Also

This can be used inside UPARAM as well

**Comment by benui-dev** [comment]
Done! Thank you!
