### ISSUE TITLE
Missing an option in meta specifiers for UPROPERTY

### ISSUE THREAD

**Issue by BBTait** [benui-dev/benui-site#12]
There is a nifty nifty specifier I found that isn't on the property specifier page

GetOptions is a meta = specifyer that will let you signify a UFUNCTION marked with CallInEditor as a getter to popular an array to pick for the UPROPERTY

IE you have ...

UPROPERTY(EditAnywhere, meta = (GetOptions = "GetStrings"))
FString MyString;

UFUNCTION(CallInEditor)
const TArray<FString>& GetStrings();

Super nifty hidden code as usual, but I thought it was worth sharing

I think it only work though if the getter function returns references, so keep that in mind.

**Comment by benui-dev** [comment]
We already have the `GetOptions` UPROPERTY:
- [benui.ca](https://benui.ca/unreal/uproperty/#getoptions)
- [uproperty.yml](https://github.com/benui-dev/UE-Specifier-Docs/blob/main/yaml/uproperty.yml#L708)

We also have the `CallInEditor` function, but as far as I know it's not required to work with `GetOptions`
https://github.com/benui-dev/UE-Specifier-Docs/blob/main/yaml/ufunction.yml
