### ISSUE TITLE
Newsletter emails get discarded due to missing header

### ISSUE THREAD

**Issue by Antonrr** [benui-dev/benui-site#14]
Hello!

Trying to subscribe to the monthly newsletter I discovered that confirmation emails from tinyletter don't pass through Gmail with the following error: "Message has been blocked. Messages missing a valid messageId header are not accepted - gsmtp".

Regards,
Anton

**Comment by benui-dev** [comment]
@Antonrr is this still happening? I can try to submit a ticket with Tinyletter but I have a feeling it is out of my hands

**Comment by Antonrr** [comment]
Just checked. Yes, the issue is still present.

**Comment by benui-dev** [comment]
Newsletter is not running anymore, closing this, sorry
