### ISSUE TITLE
Delegate Signature Tool - RETVAL vs RetVal

### ISSUE THREAD

**Issue by Matt-Carey** [benui-dev/benui-site#18]
The tool at https://benui.ca/unreal/delegates-advanced/
Is super handy - though it tripped me up when using a delegate with a return value.

The tool generates "DECLARE_DELEGATE_RETVAL" in all caps, when Unreal expects "DECLARE_DELEGATE_RetVal" for example.

The example cases shown below on the site use the correct 'RetVal' casing.

**Comment by benui-dev** [comment]
Fixed! Thank you so much for posting this correction, sorry it took so long to get round to
