### ISSUE TITLE
Missing UPROPERTY meta specifier named "IncludeAssetBundles" in documentation

### ISSUE THREAD

**Issue by lsandersljungberg** [benui-dev/benui-site#20]
```
class UMyBlueprintContainer : public UOBject
{
   UPROPERTY(EditDefaultsOnly, meta = (AssetBundles="Client"))
   TSoftClassPtr<UObject> Blueprint;
}

class UMyPrimaryAsset : public UPrimaryDataAsset
{
   UPROPERTY(EditDefaultsOnly)
   TSoftObjectPtr<UMyBlueprintContainer> Container;
}
```

In the above example `Blueprint` will _not_ be added to the `UMyPrimaryAsset`s `AssetBundleData`. To make this happen we need to change the `UPROPERTY` to:

```
   UPROPERTY(EditDefaultsOnly, meta = (IncludeAssetBundles))
   TSoftObjectPtr<UMyBlueprintContainer> Container;
```

I can't find more about it on the web other than a patch note: https://docs.unrealengine.com/4.26/en-US/WhatsNew/Builds/ReleaseNotes/4_23/

**Comment by benui-dev** [comment]
Added to main repo, will merge into the site later
