### ISSUE TITLE
UCLASS Display meta specifier incorrectly lists PrioritizeCategories param type as comma-separated category names

### ISSUE THREAD

**Issue by JacquelineMayne** [benui-dev/benui-site#21]
On the [PrioritizeCategories](https://benui.ca/unreal/uclass/#prioritizecategories) section of the UCLASS Metaspecifiers page, the "type" that this param is listed as accepting is "string (comma-separated category names)", but looking at the Unreal code it's split on spaces not commas.

`\UE5\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp (line 6165 - 6172)`
```
void UClass::GetPrioritizeCategories(TArray<FString>& OutPrioritizedCategories) const
{
	static const FName NAME_PrioritizeCategories(TEXT("PrioritizeCategories"));
	if (const FString* PrioritizeCategories = FindMetaData(NAME_PrioritizeCategories))
	{
		PrioritizeCategories->ParseIntoArray(OutPrioritizedCategories, TEXT(" "), true);
	}
}
```

**Comment by benui-dev** [comment]
Fixed! Thank you so much!
