### ISSUE TITLE
Advanced delegates tutorial includes incorrect information about UFUNCTION

### ISSUE THREAD

**Issue by sswires** [benui-dev/benui-site#23]
Hi,

In the advanced delegates tutorial (https://benui.ca/unreal/delegates-advanced/) the following is said about a non-dynamic delegate:
```cpp
// BindUObject requires that the target be a UObject, and that the function
// be a UFUNCTION()
OnScoreChangedDelegate.BindUObject(this, &ThisClass::OnScoreChanged);
```

and for multicast

```cpp
// AddUObject requires that the target be a UObject, and that the function
// be a UFUNCTION()
OnScoreChangedDelegate.AddUObject(this, &ThisClass::OnScoreChanged);
```

This is incorrect. Bind/AddUObject does not require UFUNCTION and never has.

Thanks.

**Comment by benui-dev** [comment]
Fixed! Sorry for the delay on this, and thank you again for the correction.
