### ISSUE TITLE
"All UPROPERTIES" page is missing information for GetKeyOptions on TMaps

### ISSUE THREAD

**Issue by Victov** [benui-dev/benui-site#25]
TMaps support a fantastic feature called GetKeyOptions that changes the more "open ended" keys (like FName or FString) to no longer be a text field, but become a dropdown instead. This allows you to create code that works based on FNames, but without having to worry about invalid keys.

This feature is missing from the [ALL UPROPERTIES](https://benui.ca/unreal/uproperty/) page.

.h
```
public:
	UPROPERTY(EditAnywhere, Meta=(GetKeyOptions="GetKeyOptions"))
	TMap<FName, FLoot> MyLoot;

private:
	UFUNCTION()
	TArray<FName> GetKeyOptions() const;
```

.cpp

```
TArray<FName> ULootTable::GetKeyOptions() const
{
	if (const UDataTable* const LootDatabase = GetLootDatabase())
	{
		TArray<FName> Result;
		LootDatabase->GetRowMap().GetKeys(Result);
		return Result;
	}

	return TArray<FName>();
}
```

Result:
![image](https://github.com/benui-dev/benui-site/assets/6769990/2868abaf-81a8-4d13-8bf5-b58b9effd5a0)

**Comment by benui-dev** [comment]
Okay this should be fixed now, thank you so much for your screenshot and snippet!
