### ISSUE TITLE
UPROPERTY specifier "RequiredAssetDataTags" Outdated for UE5

### ISSUE THREAD

**Issue by TremaineDM** [benui-dev/benui-site#26]
The original example of :

> UPROPERTY(EditDefaultsOnly, meta=(RequiredAssetDataTags="RowStructure=ImageRow"))

no longer works, to get it working I had to write out specifier like so:

> UPROPERTY(EditDefaultsOnly, meta=(RequiredAssetDataTags="RowStructure=/Script/MyProject.ImageRow"))

with "MyProject" being the project or plugin name that the row structure class was located in.

**Comment by benui-dev** [comment]
A year later... and I finally did it. The website should update soon. Thank you!
