### ISSUE TITLE
UFUNCTION() BlueprintImplementableEvent description is super vague

### ISSUE THREAD

**Issue by AudreyYarmo** [benui-dev/benui-site#27]
Could you please change the description for BlueprintImplementableEvent to something along the lines of 

BlueprintImplementableEvent
Functions using BlueprintImplementableEvent can not be overridden in C++, but can be overridden in any Blueprint class that implements or inherits your interface.

Source:
https://docs.unrealengine.com/5.3/en-US/interfaces-in-unreal-engine/

**Comment by benui-dev** [comment]
This is a great point, thank you! Sorry it took so long to add, it should be on the site in the next day
