### ISSUE TITLE
Please update TOptional page to include example returning TOptional that uses NullOpt

### ISSUE THREAD

**Issue by bjbrewster** [benui-dev/benui-site#28]
Since the official Unreal documentation is rubbish, can you please update your excellent page on TOptional to include an example returning a TOptional type? It can be confusing how to return an unset/null value. 

Like `std::nullopt` for `std::optional`, Unreal includes a `NullOpt` var but it's not documented anywhere but the source code.

Something like:
```
template <typename T>
TOptional<T> TryConvertEnumNameToValue(const FString& Name)
{
	UEnum* EnumClass = StaticEnum<T>();

	int64 index = EnumClass->GetIndexByNameString(Name, EGetByNameFlags::CaseSensitive);
	if (index == INDEX_NONE)
		return NullOpt; // or TOptional<T>() or {}

	return static_cast<T>(EnumClass->GetValueByIndex(index));
}

UENUM()
enum class ETest { None, Foo, Bar };

ETest value = TryConvertEnumNameToValue<ETest>("Foo").Get(ETest::None)
check(value == ETest::Foo);
```

**Comment by benui-dev** [comment]
Only an entire year later... but I pushed a change to the page with your code suggestion. Thank you so much, sorry it took so long!
