### ISSUE TITLE
Broken snippet markup on the page: Coding Standards I use in 2024

### ISSUE THREAD

**Issue by xalagor** [benui-dev/benui-site#30]
Page [Coding Standards I use in 2024](https://benui.ca/unreal/2024-coding-standard/):

Some of the code has gotten beyond the snippets, they are hard to read.

<details><summary>Screenshot</summary>
<p>

![Screenshot_20240621_201215_edit_4077445069689](https://github.com/benui-dev/benui-site/assets/6804367/cc636427-eb04-45fe-a156-30ac8098baaa)

</p>
</details>

**Comment by benui-dev** [comment]
Not sure when/how I fixed it but it looks OK right now. Thank you for the heads-up, sorry it took me so long to reply!
