### ISSUE TITLE
Delegate signature tool should include trailing semicolon

### ISSUE THREAD

**Issue by cfstras** [benui-dev/benui-site#31]
https://benui.ca/unreal/delegates-advanced/

First of all, thanks for your great articles! They're really insightful and I refer to them often.

<img width="512" alt="image" src="https://github.com/user-attachments/assets/611d8c40-ed6b-494f-84e8-b63a8f73786d">

Some people might stumble over this - seemingly Unreal lets you get away with defining a non-dynamic delegate like this:
```cpp
DECLARE_DELEGATE(FMyEvent)
```

But not a dynamic one:
```cpp
DECLARE_DYNAMIC_DELEGATE(FMyEvent)
```
> Found 'UCLASS' when expecting ';' while parsing delegate declaration [UnrealHeaderTool Error]

Probably best to just include the trailing semicolon in the little helper tool you have in the article.

Thanks!

**Comment by benui-dev** [comment]
Sorry for the delay on this, I added the semicolon, great point!
