### ISSUE TITLE
FText::Format Escape character usage is described wrong

### ISSUE THREAD

**Issue by dobacetr** [benui-dev/benui-site#33]
At [Using Curly Brace in FormatText](https://benui.ca/unreal/using-curly-brace-in-formattext/), the escape sequence is described as:

> Wrap them in backticks

 or 

> surround your text with backtick

The proper escape sequence is to just lead with a single backtick as an escape character. 

### Example
I want to surround my Text with curly braces (to use it as a FTextFormat).

```
static FText FTextFormatIntoArgument(const FText& InText) {
    static const FTextFormat Fmt{ INVTEXT(
        "`{{0}`}" // Escape the first { and the last } with `,
    ) };
// Assuming InText = "MyArg"; Result is "{MyArg}";
    return FText::Format(Fmt, InText); 
}
```

**Comment by benui-dev** [comment]
Thank you for this correction, I have updated my site, it should rebuild in a few mins.
