### ISSUE TITLE
PR blog has a misleading image

### ISSUE THREAD

**Issue by WizardCell** [benui-dev/benui-site#4]
Hey Ben, I came upon your post and found it really helpful: https://benui.ca/unreal/make-pull-request/#5-create-the-pull-request
Though I was a bit confused which branch I should merge to(release or master) as I guessed that would be `master`, considering that's the branch I made a branch from.
What confused me was this image:
![image](https://user-images.githubusercontent.com/25373592/163693178-899681f3-f97d-430a-856f-479a8ebfab5a.png)

It should be `master` instead of `release`. I also noticed you was confused with this lately heh: [https://twitter.com/_benui/status/1451361042223697938?](https://twitter.com/_benui/status/1451361042223697938?s=20&t=1WXIiBd7hUnJ6Vca8lu_tw)

**Comment by benui-dev** [comment]
Fixed! Thank you!
