### ISSUE TITLE
Uncompleted sentence & one tiny inconsistency

### ISSUE THREAD

**Issue by WizardCell** [benui-dev/benui-site#5]
**1.** Unreal UI Tips blog has an uncompleted sentence as can be seen in the following image:
![image](https://user-images.githubusercontent.com/25373592/163694047-11c2c1cb-4fd3-4653-b953-be045ef0e444.png)
I would guess the absent word there is "editor".

**2.** Another issue that caught my eye, is the fact that this was mentioned at some point:
![image](https://user-images.githubusercontent.com/25373592/163694126-a70e11c3-b34e-440a-8873-6a0d7b08bf94.png)
And at the end of the blog I saw this:
![image](https://user-images.githubusercontent.com/25373592/163694141-00136561-9d32-47c5-b6ee-da8d48359146.png)
For the sake of consistency, I would love if `Icon` gets added as another acceptable option as a suffix, or that `Icon` suffix there gets edited to be `Image`.

**3.** Although this one doesn't seem like a big deal, my detail oriented personality makes me talk about it:
![image](https://user-images.githubusercontent.com/25373592/163694220-ec7193c3-944d-4394-8ced-904c66c53075.png)
I guess the you wanted the highlight style there but for some reason, it didn't work out for you. Guessed you might want to look into it.

**Comment by benui-dev** [comment]
Fixed, thank you!
