### ISSUE TITLE
UPARAM can be used to rename the return value pin

### ISSUE THREAD

**Issue by dtaralla** [benui-dev/benui-site#9]
Hey Ben!

I came across this thread: https://forums.unrealengine.com/t/changing-return-value-display-in-bp/331749/8

Then I went to your page to confirm the finding, but didn't find it. However, I tried it and it still works in UE 4.27 (no reason why it wouldn't on UE5 either  I assume).

You might want to add this trick to your UPARAM page :)

Cheers!

**Comment by benui-dev** [comment]
Thanks @dtaralla, I added this in this commit. Thank you!
https://github.com/benui-dev/UE-Specifier-Docs/commit/a8735849b5db702f0730174e0012a98d5c308d97
